# For security reasons this is a separate GitHub workflow, see https://github.com/google/gson/issues/2429#issuecomment-1622522842
# Once https://github.com/mojohaus/animal-sniffer/issues/252 or https://github.com/mojohaus/animal-sniffer/pull/253
# are resolved, can consider adjusting pom.xml to include this as part of normal Maven build
# Run 'test' phase because plugin normally expects to be executed after tests have been compiled
# Have to skip 'test-jpms' module because it requires that full Gson JAR has been built

name: Modified Check Android compatibility
permissions:
  contents: read
jobs:
  check-android-compatibility:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-check-android-compatibility.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/gson/gson', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - run: touch optcd-3.txt
    - name: Set up JDK 11
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
      with:
        distribution: temurin
        java-version: '11'
        cache: maven
    - run: touch optcd-4.txt
    - name: Check Android compatibility
      run: |-
        # Run 'test' phase because plugin normally expects to be executed after tests have been compiled
        # Have to skip 'test-jpms' module because it requires that full Gson JAR has been built
        mvn --batch-mode --no-transfer-progress test animal-sniffer:check@check-android-compatibility -DskipTests --projects '!test-jpms'
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-check-android-compatibility
        path: /home/runner/inotifywait-log-check-android-compatibility.csv
    name: check-android-compatibility
'on':
- push
- workflow_dispatch
